--
-- PostgreSQL database dump
--

-- Dumped from database version 11.3
-- Dumped by pg_dump version 11.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: artists; Type: TABLE; Schema: public;
--

DROP DATABASE test_tattoo_shop;
CREATE DATABASE test_tattoo_shop;
\c test_tattoo_shop;

CREATE TABLE public.artists (
    id integer NOT NULL,
    name text,
    phone text,
    styles text,
    image_link text NULL,
    instagram_link text NULL,
    email text NULL
);

ALTER TABLE public.artists OWNER TO postgres;

--
-- Name: artists_id_seq; Type: SEQUENCE; Schema: public;
--

CREATE SEQUENCE public.artists_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE public.artists_id_seq OWNER TO postgres;

--
-- Name: artists_id_seq; Type: SEQUENCE OWNED BY; Schema: public;
--

ALTER SEQUENCE public.artists_id_seq OWNED BY public.artists.id;

--
-- Name: clients; Type: TABLE; Schema: public;
--

CREATE TABLE public.clients (
    id integer NOT NULL,
    name text,
    email text NULL,
    phone text,
    address text
);


ALTER TABLE public.clients OWNER TO postgres;

--
-- Name: clients_id_seq; Type: SEQUENCE; Schema: public;
--

CREATE SEQUENCE public.clients_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE public.clients_id_seq OWNER TO postgres;


--
-- Name: clients_id_seq; Type: SEQUENCE OWNED BY; Schema: public;
--

ALTER SEQUENCE public.clients_id_seq OWNED BY public.clients.id;

--
-- Name: appointments; Type TABLE; Schema: public;
--

CREATE TABLE public.appointments (
    id integer NOT NULL,
    artist integer,
    client integer,
    appointment_date DATE NOT NULL DEFAULT CURRENT_DATE
);

ALTER TABLE public.appointments OWNER TO postgres;

--
-- Name: appointments_id_seq; Type: SEQUENCE; Schema: public;
--

CREATE SEQUENCE public.appointments_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER TABLE public.appointments_id_seq OWNER TO postgres;


--
-- Name: artists id; Type: DEFAULT; Schema: public;
--

ALTER TABLE ONLY public.artists ALTER COLUMN id SET DEFAULT nextval('public.artists_id_seq'::regclass);


--
-- Name: clients id; Type: DEFAULT; Schema: public; Owner: caryn
--

ALTER TABLE ONLY public.clients ALTER COLUMN id SET DEFAULT nextval('public.clients_id_seq'::regclass);

--
-- Name: clients id; Type: DEFAULT; Schema: public; Owner: caryn
--

ALTER TABLE ONLY public.appointments ALTER COLUMN id SET DEFAULT nextval('public.appointments_id_seq'::regclass);

--
-- Data for Name: artists; Type: TABLE DATA; Schema: public;
--

COPY public.artists (id, name, phone, styles, image_link, instagram_link, email) FROM stdin;
1	Kobe	123-432-4231	Neo	NULL	NULL	NULL
2	Lebron	142-323-6123	Traditional	NULL	NULL	NULL
3	Dwyane	313-123-5234	Japenese	NULL	NULL	NULL
4	Michael	620-132-4923	Japanese	NULL	NULL	NULL
\.

COPY public.clients (id, name, email, phone, address) FROM stdin;
1	Patrick	NULL	NULL	NULL
2	Deshaun	NULL	NULL	NULL
3	Aaron	NULL	NULL	NULL
4	Lamar	NULL	NULL	NULL
5	Jalen	NULL	NULL	NULL
\.

COPY public.appointments (id, artist, client, appointment_date) FROM stdin;
1	1	1	2021-03-06
2	2	2	2021-07-04
3	3	2	2021-08-09
4	3	4	2021-01-01
\.

--
-- Name: artists_id_seq; Type: SEQUENCE SET; Schema: public;
--

SELECT pg_catalog.setval('public.artists_id_seq', 4, true);

--
-- Name: clients_id_seq; Type: SEQUENCE SET; Schema: public;
--

SELECT pg_catalog.setval('public.clients_id_seq', 5, true);

--
-- Name: appointments_id_seq; Type: SEQUENCE SET; Schema: public;
--

SELECT pg_catalog.setval('public.appointments_id_seq', 4, true);

--
-- Name: artists artists_pkey; Type: CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY public.artists
    ADD CONSTRAINT artists_pkey PRIMARY KEY (id);

--
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);

--
-- Name: appointments appointments_pkey; Type: CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT appointments_pkey PRIMARY KEY (id);

--
-- Name: clients category; Type: FK CONSTRAINT; Schema: public;
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT artist FOREIGN KEY (artist) REFERENCES public.artists(id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT client FOREIGN KEY (client) REFERENCES public.clients(id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--
