"""empty message

Revision ID: 2f00b28ce7d6
Revises: f396d5114836
Create Date: 2021-01-04 14:34:28.174747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f00b28ce7d6'
down_revision = 'f396d5114836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('client', 'appointment', 'clients', ['client'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key('artist', 'appointment', 'artists', ['artist'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###
