"""empty message

Revision ID: 6474ed00f710
Revises: 9999e630af3b
Create Date: 2020-12-29 17:13:35.418152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6474ed00f710'
down_revision = '9999e630af3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artist', 'appointment', type_='foreignkey')
    op.drop_constraint('client', 'appointment', type_='foreignkey')
    op.create_foreign_key(None, 'appointment', 'artists', ['artist'], ['id'])
    op.create_foreign_key(None, 'appointment', 'clients', ['client'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.create_foreign_key('client', 'appointment', 'clients', ['client'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key('artist', 'appointment', 'artists', ['artist'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###
